tic_settings:
  product: TIC_PRODUCT_T249
  auto_clear_driver_error: True
  ignore_err_line_high: True
  serial_crc_enabled: False
  command_timeout: 0
  max_speed: 5000000                # pulses/s * 10^-4
  starting_speed: 0                   # pulses/s * 10^-4
  max_accel: 10000                  # pulses/s^2 * 10^-2
  max_decel: 10000                  # pulses/s^2 * 10^-2
  step_mode: TIC_STEP_MODE_MICROSTEP32 
  current_limit: 1000 # mA (see table in Pololu manual for acceptable values)
  
  # Disabled Decay mode for T249 because decay mode of the Tic T249 is not configurable
  # Tic T249 features Toshiba’s Advanced Dynamic Mixed Decay (ADMD) technology, which
  # dynamically switches between slow and fast decay modes based on the actual motor current
  # decay_mode: TIC_DECAY_MODE_T825_FAST 
  pin_settings:
    - pin_num: TIC_PIN_NUM_RX
      func: TIC_PIN_FUNC_USER_INPUT
      pullup: True
      analog: False